-- +goose Up

-- Baseline schema generated by squashing migrations 000001 through 000021.
-- Production had not started when this baseline was created.

-- ---- 000001_init.sql ----
CREATE TABLE inbound_sources (
    id uuid PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    auth_mode text NOT NULL DEFAULT 'token'
        CHECK (auth_mode IN ('token', 'hmac', 'token_and_hmac', 'none')),
    auth_token text,
    hmac_secret text,
    ip_allowlist text[] NOT NULL DEFAULT ARRAY[]::text[],
    compat_mode text NOT NULL DEFAULT 'standard',
    inbound_dedupe_enabled boolean NOT NULL DEFAULT false,
    inbound_dedupe_strategy text NOT NULL DEFAULT 'payload_hash'
        CHECK (inbound_dedupe_strategy = 'payload_hash'),
    inbound_dedupe_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    rate_limit_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    do_not_disturb_config jsonb NOT NULL DEFAULT '{"enabled":false,"windows":[]}'::jsonb,
    latest_payload_sample jsonb,
    latest_payload_sample_updated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE delivery_channels (
    id uuid PRIMARY KEY,
    provider_type text NOT NULL
        CHECK (provider_type IN ('wecom', 'feishu', 'dingtalk', 'email', 'sms', 'self', 'webhook')),
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    auth_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    token_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    send_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    rate_limit_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    concurrency_limit integer NOT NULL DEFAULT 5 CHECK (concurrency_limit > 0),
    timeout_ms integer NOT NULL DEFAULT 5000 CHECK (timeout_ms > 0),
    retry_policy jsonb NOT NULL DEFAULT '{"max_attempts":3}'::jsonb,
    dead_letter_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE provider_capabilities (
    id uuid PRIMARY KEY,
    provider_type text NOT NULL
        CHECK (provider_type IN ('wecom', 'feishu', 'dingtalk', 'email', 'sms', 'self', 'webhook')),
    message_type text NOT NULL,
    message_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    recipient_required boolean NOT NULL DEFAULT true,
    allow_no_recipient boolean NOT NULL DEFAULT false,
    recipient_field_name text,
    recipient_location text NOT NULL DEFAULT 'body'
        CHECK (recipient_location IN ('query', 'header', 'body', 'path', 'none')),
    recipient_path text,
    recipient_format text NOT NULL DEFAULT 'string'
        CHECK (recipient_format IN ('string', 'array', 'pipe_string', 'comma_string', 'object_array')),
    identity_kind text,
    token_location text NOT NULL DEFAULT 'none'
        CHECK (token_location IN ('query', 'header', 'body', 'path', 'none')),
    token_field_name text,
    request_examples jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_type, message_type)
);

CREATE TABLE org_units (
    id uuid PRIMARY KEY,
    parent_id uuid REFERENCES org_units(id) ON DELETE SET NULL,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    path text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id uuid PRIMARY KEY,
    display_name text NOT NULL,
    primary_org_id uuid REFERENCES org_units(id) ON DELETE SET NULL,
    enabled boolean NOT NULL DEFAULT true,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_org_memberships (
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    org_id uuid NOT NULL REFERENCES org_units(id) ON DELETE CASCADE,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, org_id)
);

CREATE TABLE user_identities (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_type text NOT NULL DEFAULT 'common',
    identity_kind text NOT NULL,
    identity_value text NOT NULL,
    verified boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_type, identity_kind, identity_value)
);

CREATE TABLE match_groups (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    group_type text NOT NULL,
    description text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE match_group_items (
    id uuid PRIMARY KEY,
    group_id uuid NOT NULL REFERENCES match_groups(id) ON DELETE CASCADE,
    value text NOT NULL,
    value_type text NOT NULL DEFAULT 'text',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (group_id, value)
);

CREATE TABLE recipient_groups (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    user_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    org_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    excluded_user_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    excluded_org_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE templates (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    source_id uuid REFERENCES inbound_sources(id) ON DELETE SET NULL,
    enabled boolean NOT NULL DEFAULT true,
    current_version_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE template_versions (
    id uuid PRIMARY KEY,
    template_id uuid NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
    version_no integer NOT NULL CHECK (version_no > 0),
    message_type text NOT NULL,
    target_provider_type text NOT NULL,
    template_engine text NOT NULL DEFAULT 'pongo2',
    template_syntax_version text NOT NULL DEFAULT 'jinja-like-v1',
    template_body text NOT NULL,
    message_body_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    sample_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    compiled_preview jsonb,
    used_variables text[] NOT NULL DEFAULT ARRAY[]::text[],
    allowed_filters text[] NOT NULL DEFAULT ARRAY[]::text[],
    validation_status text NOT NULL DEFAULT 'draft'
        CHECK (validation_status IN ('draft', 'valid', 'invalid')),
    validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb,
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (template_id, version_no)
);

ALTER TABLE templates
    ADD CONSTRAINT fk_templates_current_version
    FOREIGN KEY (current_version_id) REFERENCES template_versions(id) ON DELETE SET NULL;

CREATE TABLE route_flows (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES inbound_sources(id) ON DELETE CASCADE,
    name text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    mode text NOT NULL DEFAULT 'table' CHECK (mode IN ('canvas', 'table')),
    current_version_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_route_flows_enabled_source
    ON route_flows(source_id)
    WHERE enabled;

CREATE TABLE route_versions (
    id uuid PRIMARY KEY,
    flow_id uuid NOT NULL REFERENCES route_flows(id) ON DELETE CASCADE,
    version_no integer NOT NULL CHECK (version_no > 0),
    draft_base_version_id uuid,
    draft_base_version_no integer CHECK (draft_base_version_no IS NULL OR draft_base_version_no > 0),
    canvas_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    compiled_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
    validation_status text NOT NULL DEFAULT 'draft'
        CHECK (validation_status IN ('draft', 'valid', 'invalid')),
    validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb,
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (flow_id, version_no)
);

ALTER TABLE route_versions
    ADD CONSTRAINT fk_route_versions_draft_base
    FOREIGN KEY (draft_base_version_id) REFERENCES route_versions(id) ON DELETE SET NULL;

ALTER TABLE route_flows
    ADD CONSTRAINT fk_route_flows_current_version
    FOREIGN KEY (current_version_id) REFERENCES route_versions(id) ON DELETE SET NULL;

CREATE TABLE route_rules (
    id uuid PRIMARY KEY,
    flow_id uuid NOT NULL REFERENCES route_flows(id) ON DELETE CASCADE,
    version_id uuid NOT NULL REFERENCES route_versions(id) ON DELETE CASCADE,
    rule_key uuid NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    name text NOT NULL,
    condition_tree jsonb NOT NULL DEFAULT '{}'::jsonb,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (version_id, rule_key),
    UNIQUE (version_id, sort_order)
);

CREATE TABLE route_actions (
    id uuid PRIMARY KEY,
    rule_id uuid NOT NULL REFERENCES route_rules(id) ON DELETE CASCADE,
    template_version_id uuid REFERENCES template_versions(id) ON DELETE SET NULL,
    channel_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    recipient_strategy jsonb NOT NULL DEFAULT '{}'::jsonb,
    send_dedupe_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    failure_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE route_rule_counters (
    flow_id uuid NOT NULL REFERENCES route_flows(id) ON DELETE CASCADE,
    rule_key uuid NOT NULL,
    hit_count integer NOT NULL DEFAULT 0 CHECK (hit_count >= 0 AND hit_count <= 99999),
    last_hit_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (flow_id, rule_key)
);

CREATE TABLE message_records (
    id uuid PRIMARY KEY,
    trace_id text NOT NULL UNIQUE,
    source_id uuid NOT NULL REFERENCES inbound_sources(id) ON DELETE RESTRICT,
    received_at timestamptz NOT NULL DEFAULT now(),
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    payload_hash text NOT NULL,
    status text NOT NULL DEFAULT 'accepted'
        CHECK (status IN ('accepted', 'deduped', 'silenced', 'planned', 'partial_sent', 'sent', 'failed', 'no_route')),
    matched_flow_id uuid REFERENCES route_flows(id) ON DELETE SET NULL,
    matched_rule_ids uuid[] NOT NULL DEFAULT ARRAY[]::uuid[],
    error_code text,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE delivery_attempts (
    id uuid PRIMARY KEY,
    message_id uuid NOT NULL REFERENCES message_records(id) ON DELETE CASCADE,
    channel_id uuid NOT NULL REFERENCES delivery_channels(id) ON DELETE RESTRICT,
    template_version_id uuid REFERENCES template_versions(id) ON DELETE SET NULL,
    recipient_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    request_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'sent', 'failed', 'deduped', 'skipped')),
    error_code text,
    error_message text,
    duration_ms integer CHECK (duration_ms IS NULL OR duration_ms >= 0),
    attempt_no integer NOT NULL DEFAULT 1 CHECK (attempt_no > 0),
    next_retry_at timestamptz,
    dead_lettered_at timestamptz,
    queued_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dedupe_keys (
    id uuid PRIMARY KEY,
    scope text NOT NULL CHECK (scope IN ('inbound', 'send')),
    source_id uuid REFERENCES inbound_sources(id) ON DELETE CASCADE,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE CASCADE,
    dedupe_key text NOT NULL,
    expires_at timestamptz NOT NULL,
    message_id uuid REFERENCES message_records(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (scope = 'inbound' AND source_id IS NOT NULL AND channel_id IS NULL)
        OR
        (scope = 'send' AND channel_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX ux_dedupe_inbound_source_key
    ON dedupe_keys(scope, source_id, dedupe_key)
    WHERE scope = 'inbound' AND source_id IS NOT NULL;

CREATE UNIQUE INDEX ux_dedupe_send_channel_key
    ON dedupe_keys(scope, channel_id, dedupe_key)
    WHERE scope = 'send' AND channel_id IS NOT NULL;

CREATE TABLE jobs (
    id uuid PRIMARY KEY,
    type text NOT NULL
        CHECK (type IN ('route_plan', 'send_message', 'stats_aggregate', 'retention_cleanup', 'dead_letter_replay')),
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'done', 'failed', 'dead')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    run_at timestamptz NOT NULL DEFAULT now(),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts integer NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
    locked_by text,
    locked_at timestamptz,
    heartbeat_at timestamptz,
    processing_timeout_seconds integer CHECK (processing_timeout_seconds IS NULL OR processing_timeout_seconds > 0),
    last_error text,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    priority integer NOT NULL DEFAULT 100,
    queue_key text,
    started_at timestamptz,
    finished_at timestamptz,
    duration_ms integer CHECK (duration_ms IS NULL OR duration_ms >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dead_letter_jobs (
    id uuid PRIMARY KEY,
    job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,
    type text NOT NULL
        CHECK (type IN ('route_plan', 'send_message', 'stats_aggregate', 'retention_cleanup', 'dead_letter_replay')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    error_code text,
    error_message text NOT NULL,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    dead_lettered_at timestamptz NOT NULL DEFAULT now(),
    replayed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE worker_metrics (
    id uuid PRIMARY KEY,
    bucket_start timestamptz NOT NULL,
    worker_type text NOT NULL CHECK (worker_type IN ('planning', 'sending', 'maintenance')),
    job_type text NOT NULL
        CHECK (job_type IN ('route_plan', 'send_message', 'stats_aggregate', 'retention_cleanup', 'dead_letter_replay')),
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    processed integer NOT NULL DEFAULT 0 CHECK (processed >= 0),
    success integer NOT NULL DEFAULT 0 CHECK (success >= 0),
    failed integer NOT NULL DEFAULT 0 CHECK (failed >= 0),
    rate_limited integer NOT NULL DEFAULT 0 CHECK (rate_limited >= 0),
    dead_lettered integer NOT NULL DEFAULT 0 CHECK (dead_lettered >= 0),
    avg_duration_ms integer CHECK (avg_duration_ms IS NULL OR avg_duration_ms >= 0),
    p95_duration_ms integer CHECK (p95_duration_ms IS NULL OR p95_duration_ms >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (bucket_start, worker_type, job_type, channel_id)
);

CREATE TABLE route_rule_metrics (
    id uuid PRIMARY KEY,
    bucket_start timestamptz NOT NULL,
    source_id uuid NOT NULL REFERENCES inbound_sources(id) ON DELETE CASCADE,
    flow_id uuid NOT NULL REFERENCES route_flows(id) ON DELETE CASCADE,
    route_version_id uuid NOT NULL REFERENCES route_versions(id) ON DELETE CASCADE,
    rule_id uuid NOT NULL REFERENCES route_rules(id) ON DELETE CASCADE,
    evaluated integer NOT NULL DEFAULT 0 CHECK (evaluated >= 0),
    matched integer NOT NULL DEFAULT 0 CHECK (matched >= 0),
    avg_duration_ms integer CHECK (avg_duration_ms IS NULL OR avg_duration_ms >= 0),
    p95_duration_ms integer CHECK (p95_duration_ms IS NULL OR p95_duration_ms >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (bucket_start, rule_id)
);

CREATE TABLE admin_users (
    id uuid PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    display_name text NOT NULL DEFAULT '系统管理员',
    must_change_password boolean NOT NULL DEFAULT true,
    enabled boolean NOT NULL DEFAULT true,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE setup_state (
    singleton_id integer PRIMARY KEY DEFAULT 1 CHECK (singleton_id = 1),
    initialized boolean NOT NULL DEFAULT false,
    initialized_admin_id uuid REFERENCES admin_users(id) ON DELETE SET NULL,
    initialized_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
    id uuid PRIMARY KEY,
    actor_admin_id uuid REFERENCES admin_users(id) ON DELETE SET NULL,
    actor_username text,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text,
    request_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip_address inet,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE hourly_stats (
    id uuid PRIMARY KEY,
    bucket_start timestamptz NOT NULL,
    source_id uuid REFERENCES inbound_sources(id) ON DELETE SET NULL,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    inbound_count integer NOT NULL DEFAULT 0 CHECK (inbound_count >= 0),
    outbound_count integer NOT NULL DEFAULT 0 CHECK (outbound_count >= 0),
    success_count integer NOT NULL DEFAULT 0 CHECK (success_count >= 0),
    failed_count integer NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
    deduped_count integer NOT NULL DEFAULT 0 CHECK (deduped_count >= 0),
    avg_duration_ms integer CHECK (avg_duration_ms IS NULL OR avg_duration_ms >= 0),
    p95_duration_ms integer CHECK (p95_duration_ms IS NULL OR p95_duration_ms >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE daily_stats (
    id uuid PRIMARY KEY,
    bucket_date date NOT NULL,
    source_id uuid REFERENCES inbound_sources(id) ON DELETE SET NULL,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    inbound_count integer NOT NULL DEFAULT 0 CHECK (inbound_count >= 0),
    outbound_count integer NOT NULL DEFAULT 0 CHECK (outbound_count >= 0),
    success_count integer NOT NULL DEFAULT 0 CHECK (success_count >= 0),
    failed_count integer NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
    deduped_count integer NOT NULL DEFAULT 0 CHECK (deduped_count >= 0),
    avg_duration_ms integer CHECK (avg_duration_ms IS NULL OR avg_duration_ms >= 0),
    p95_duration_ms integer CHECK (p95_duration_ms IS NULL OR p95_duration_ms >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_org_units_parent_sort ON org_units(parent_id, sort_order, name);
CREATE INDEX idx_org_units_path ON org_units(path);
CREATE INDEX idx_users_primary_org ON users(primary_org_id);
CREATE INDEX idx_user_org_memberships_org ON user_org_memberships(org_id);
CREATE INDEX idx_user_identities_lookup ON user_identities(provider_type, identity_kind, identity_value);
CREATE INDEX idx_match_group_items_group ON match_group_items(group_id, value);
CREATE INDEX idx_templates_source ON templates(source_id);
CREATE INDEX idx_template_versions_template ON template_versions(template_id, version_no DESC);
CREATE INDEX idx_route_rules_order ON route_rules(flow_id, version_id, sort_order);
CREATE INDEX idx_route_actions_rule ON route_actions(rule_id);
CREATE INDEX idx_route_rule_counters_lookup ON route_rule_counters(flow_id, rule_key);

CREATE INDEX idx_message_records_received_at ON message_records(received_at DESC);
CREATE INDEX idx_message_records_source_received ON message_records(source_id, received_at DESC);
CREATE INDEX idx_message_records_status_received ON message_records(status, received_at DESC);
CREATE INDEX idx_delivery_attempts_message ON delivery_attempts(message_id);
CREATE INDEX idx_delivery_attempts_channel_queued ON delivery_attempts(channel_id, queued_at DESC);
CREATE INDEX idx_delivery_attempts_status_queued ON delivery_attempts(status, queued_at);

CREATE INDEX idx_jobs_status_run_at ON jobs(status, run_at, priority);
CREATE INDEX idx_jobs_type_status_run_at ON jobs(type, status, run_at);
CREATE INDEX idx_jobs_channel_status_run_at ON jobs(channel_id, status, run_at);
CREATE INDEX idx_jobs_queue_status_run_at ON jobs(queue_key, status, run_at);
CREATE INDEX idx_jobs_processing_recovery ON jobs(status, heartbeat_at, locked_at)
    WHERE status = 'processing';
CREATE INDEX idx_jobs_retention_finished ON jobs(finished_at)
    WHERE finished_at IS NOT NULL;

CREATE INDEX idx_dead_letter_jobs_dead_lettered ON dead_letter_jobs(dead_lettered_at DESC);
CREATE INDEX idx_dead_letter_jobs_channel_dead_lettered ON dead_letter_jobs(channel_id, dead_lettered_at DESC);
CREATE INDEX idx_dedupe_keys_expires_at ON dedupe_keys(expires_at);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_worker_metrics_bucket_job ON worker_metrics(bucket_start DESC, job_type);
CREATE INDEX idx_worker_metrics_channel_bucket ON worker_metrics(channel_id, bucket_start DESC);
CREATE INDEX idx_route_rule_metrics_rule_bucket ON route_rule_metrics(rule_id, bucket_start DESC);
CREATE INDEX idx_hourly_stats_bucket ON hourly_stats(bucket_start DESC);
CREATE INDEX idx_daily_stats_bucket ON daily_stats(bucket_date DESC);

INSERT INTO setup_state (singleton_id, initialized)
VALUES (1, false)
ON CONFLICT (singleton_id) DO NOTHING;

-- ---- 000002_admin_sessions.sql ----
CREATE TABLE admin_sessions (
    id uuid PRIMARY KEY,
    admin_id uuid NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    user_agent text,
    ip_address inet,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz
);

CREATE INDEX idx_admin_sessions_admin ON admin_sessions(admin_id, created_at DESC);
CREATE INDEX idx_admin_sessions_active_token ON admin_sessions(token_hash)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_admin_sessions_expires_at ON admin_sessions(expires_at);

-- ---- 000003_monitoring_cleanup_state.sql ----
CREATE TABLE retention_cleanup_runs (
    id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL,
    retention_days integer NOT NULL CHECK (retention_days > 0),
    batch_size integer NOT NULL CHECK (batch_size > 0),
    deleted_jobs integer NOT NULL DEFAULT 0 CHECK (deleted_jobs >= 0),
    deleted_dead_letters integer NOT NULL DEFAULT 0 CHECK (deleted_dead_letters >= 0),
    deleted_message_records integer NOT NULL DEFAULT 0 CHECK (deleted_message_records >= 0),
    deleted_delivery_attempts integer NOT NULL DEFAULT 0 CHECK (deleted_delivery_attempts >= 0),
    deleted_dedupe_keys integer NOT NULL DEFAULT 0 CHECK (deleted_dedupe_keys >= 0),
    deleted_worker_metrics integer NOT NULL DEFAULT 0 CHECK (deleted_worker_metrics >= 0),
    deleted_route_rule_metrics integer NOT NULL DEFAULT 0 CHECK (deleted_route_rule_metrics >= 0),
    last_batch_deleted integer NOT NULL DEFAULT 0 CHECK (last_batch_deleted >= 0),
    completed boolean NOT NULL DEFAULT false,
    has_more boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_retention_cleanup_runs_started_at ON retention_cleanup_runs(started_at DESC);

-- ---- 000004_system_settings.sql ----
CREATE TABLE system_settings (
    key text PRIMARY KEY,
    value jsonb NOT NULL,
    description text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT 'system',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO system_settings (key, value, description, category)
VALUES
    ('console.polling_interval_seconds', '5'::jsonb, '管理台轮询刷新间隔秒数', 'console'),
    ('logs.retention_days', '30'::jsonb, '消息日志和运行记录保留天数', 'logs'),
    ('admin.single_account_mode', 'true'::jsonb, '一期管理员单账户模式', 'admin')
ON CONFLICT (key) DO NOTHING;

-- ---- 000005_provider_capability_metadata.sql ----
ALTER TABLE provider_capabilities
    ADD COLUMN display_name text NOT NULL DEFAULT '',
    ADD COLUMN category text NOT NULL DEFAULT '',
    ADD COLUMN credential_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN channel_config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN custom_body_allowed boolean NOT NULL DEFAULT false,
    ADD COLUMN recipient_requirement text NOT NULL DEFAULT 'system'
        CHECK (recipient_requirement IN ('none', 'system', 'payload', 'platform-specific')),
    ADD COLUMN token_strategy jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN send_api jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN success_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN retry_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN default_rate_limit jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN default_timeout_ms integer NOT NULL DEFAULT 5000 CHECK (default_timeout_ms > 0),
    ADD COLUMN default_concurrency_limit integer NOT NULL DEFAULT 5 CHECK (default_concurrency_limit > 0),
    ADD COLUMN default_retry_policy jsonb NOT NULL DEFAULT '{"max_attempts":3}'::jsonb;

-- ---- 000006_route_action_targets.sql ----
CREATE TABLE route_action_targets (
    id uuid PRIMARY KEY,
    action_id uuid NOT NULL REFERENCES route_actions(id) ON DELETE CASCADE,
    channel_id uuid NOT NULL REFERENCES delivery_channels(id) ON DELETE RESTRICT,
    template_version_id uuid NOT NULL REFERENCES template_versions(id) ON DELETE RESTRICT,
    enabled boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 10,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (action_id, sort_order)
);

CREATE INDEX idx_route_action_targets_action ON route_action_targets(action_id, sort_order);
CREATE INDEX idx_route_action_targets_channel ON route_action_targets(channel_id);
CREATE INDEX idx_route_action_targets_template ON route_action_targets(template_version_id);

WITH legacy_targets AS (
    SELECT
        action.id AS action_id,
        channels.channel_id,
        action.template_version_id,
        channels.channel_index,
        md5(action.id::text || ':' || channels.channel_id::text || ':' || channels.channel_index::text) AS digest
    FROM route_actions AS action
    CROSS JOIN LATERAL unnest(action.channel_ids) WITH ORDINALITY AS channels(channel_id, channel_index)
    WHERE action.template_version_id IS NOT NULL
)
INSERT INTO route_action_targets (
    id,
    action_id,
    channel_id,
    template_version_id,
    enabled,
    sort_order
)
SELECT
    (
        substr(digest, 1, 8) || '-' ||
        substr(digest, 9, 4) || '-' ||
        substr(digest, 13, 4) || '-' ||
        substr(digest, 17, 4) || '-' ||
        substr(digest, 21, 12)
    )::uuid,
    action_id,
    channel_id,
    template_version_id,
    true,
    channel_index * 10
FROM legacy_targets;

-- ---- 000007_provider_type_expansion.sql ----
ALTER TABLE delivery_channels
    DROP CONSTRAINT IF EXISTS delivery_channels_provider_type_check;

ALTER TABLE delivery_channels
    ADD CONSTRAINT delivery_channels_provider_type_check
    CHECK (provider_type IN (
        'wecom',
        'wecom_app',
        'wecom_robot',
        'feishu',
        'feishu_robot',
        'dingtalk',
        'dingtalk_work',
        'dingtalk_robot',
        'email',
        'sms',
        'aliyun_sms',
        'tencent_sms',
        'baidu_sms',
        'self',
        'webhook',
        'pushplus',
        'wxpusher',
        'serverchan'
    ));

ALTER TABLE provider_capabilities
    DROP CONSTRAINT IF EXISTS provider_capabilities_provider_type_check;

ALTER TABLE provider_capabilities
    ADD CONSTRAINT provider_capabilities_provider_type_check
    CHECK (provider_type IN (
        'wecom',
        'wecom_app',
        'wecom_robot',
        'feishu',
        'feishu_robot',
        'dingtalk',
        'dingtalk_work',
        'dingtalk_robot',
        'email',
        'sms',
        'aliyun_sms',
        'tencent_sms',
        'baidu_sms',
        'self',
        'webhook',
        'pushplus',
        'wxpusher',
        'serverchan'
    ));

ALTER TABLE provider_capabilities
    DROP CONSTRAINT IF EXISTS provider_capabilities_recipient_format_check;

ALTER TABLE provider_capabilities
    ADD CONSTRAINT provider_capabilities_recipient_format_check
    CHECK (recipient_format IN (
        'string',
        'array',
        'pipe_string',
        'comma_string',
        'object_array',
        'none'
    ));

ALTER TABLE provider_capabilities
    DROP CONSTRAINT IF EXISTS provider_capabilities_recipient_requirement_check;

ALTER TABLE provider_capabilities
    ADD CONSTRAINT provider_capabilities_recipient_requirement_check
    CHECK (recipient_requirement IN (
        'none',
        'system',
        'payload',
        'platform-specific',
        'system_or_channel'
    ));

-- ---- 000008_provider_type_registry.sql ----
CREATE TABLE IF NOT EXISTS provider_types (
    provider_type text PRIMARY KEY,
    display_name text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT '',
    built_in boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO provider_types (provider_type, display_name, category, built_in)
SELECT provider_type, provider_type, 'existing', false
FROM (
    SELECT DISTINCT provider_type FROM delivery_channels
    UNION
    SELECT DISTINCT provider_type FROM provider_capabilities
) existing_provider_types
ON CONFLICT (provider_type) DO UPDATE
SET updated_at = now();

INSERT INTO provider_types (provider_type, display_name, category, built_in)
VALUES
    ('wecom', 'WeCom application message (legacy alias)', 'enterprise_app', true),
    ('wecom_app', 'WeCom application message', 'enterprise_app', true),
    ('wecom_robot', 'WeCom group robot', 'enterprise_robot', true),
    ('feishu', 'Feishu application message (legacy)', 'enterprise_app', true),
    ('feishu_robot', 'Feishu app robot', 'enterprise_app', true),
    ('feishu_group', 'Feishu group message', 'enterprise_robot', true),
    ('dingtalk', 'DingTalk work message (legacy alias)', 'enterprise_app', true),
    ('dingtalk_work', 'DingTalk work message', 'enterprise_app', true),
    ('dingtalk_robot', 'DingTalk group robot', 'enterprise_robot', true),
    ('email', 'SMTP email', 'email', true),
    ('sms', 'SMS provider (legacy aggregate)', 'sms', true),
    ('aliyun_sms', 'Aliyun SMS', 'sms', true),
    ('tencent_sms', 'Tencent Cloud SMS', 'sms', true),
    ('baidu_sms', 'Baidu Cloud SMS', 'sms', true),
    ('self', 'MVP-PUSH', 'gateway', true),
    ('webhook', 'Generic Webhook', 'advanced', true),
    ('pushplus', 'PushPlus', 'personal_gateway', true),
    ('wxpusher', 'WxPusher', 'personal_gateway', true),
    ('serverchan', 'ServerChan', 'personal_gateway', true),
    ('ntfy', 'ntfy', 'self_hosted', true),
    ('gotify', 'Gotify', 'self_hosted', true),
    ('bark', 'Bark', 'personal_gateway', true),
    ('pushme', 'PushMe', 'personal_gateway', true)
ON CONFLICT (provider_type) DO UPDATE
SET display_name = EXCLUDED.display_name,
    category = EXCLUDED.category,
    built_in = EXCLUDED.built_in,
    updated_at = now();

ALTER TABLE delivery_channels
    DROP CONSTRAINT IF EXISTS delivery_channels_provider_type_check,
    DROP CONSTRAINT IF EXISTS delivery_channels_provider_type_fkey;

ALTER TABLE provider_capabilities
    DROP CONSTRAINT IF EXISTS provider_capabilities_provider_type_check,
    DROP CONSTRAINT IF EXISTS provider_capabilities_provider_type_fkey;

ALTER TABLE delivery_channels
    ADD CONSTRAINT delivery_channels_provider_type_fkey
    FOREIGN KEY (provider_type) REFERENCES provider_types(provider_type)
    ON UPDATE CASCADE;

ALTER TABLE provider_capabilities
    ADD CONSTRAINT provider_capabilities_provider_type_fkey
    FOREIGN KEY (provider_type) REFERENCES provider_types(provider_type)
    ON UPDATE CASCADE;

-- ---- 000009_source_payload_hash_dedupe_only.sql ----
UPDATE inbound_sources
SET inbound_dedupe_strategy = 'payload_hash',
    updated_at = now()
WHERE inbound_dedupe_strategy <> 'payload_hash';

ALTER TABLE inbound_sources
    DROP CONSTRAINT IF EXISTS inbound_sources_inbound_dedupe_strategy_check;

ALTER TABLE inbound_sources
    ADD CONSTRAINT inbound_sources_inbound_dedupe_strategy_check
    CHECK (inbound_dedupe_strategy = 'payload_hash');

-- ---- 000010_source_ip_allowlist_text_array.sql ----
ALTER TABLE inbound_sources
    ALTER COLUMN ip_allowlist DROP DEFAULT,
    ALTER COLUMN ip_allowlist TYPE text[] USING COALESCE(ip_allowlist::text[], ARRAY[]::text[]),
    ALTER COLUMN ip_allowlist SET DEFAULT ARRAY[]::text[];

-- ---- 000011_source_do_not_disturb.sql ----
ALTER TABLE inbound_sources
    ADD COLUMN IF NOT EXISTS do_not_disturb_config jsonb NOT NULL DEFAULT '{"enabled":false,"windows":[]}'::jsonb;

ALTER TABLE message_records
    DROP CONSTRAINT IF EXISTS message_records_status_check;

ALTER TABLE message_records
    ADD CONSTRAINT message_records_status_check
    CHECK (status IN ('accepted', 'deduped', 'silenced', 'planned', 'partial_sent', 'sent', 'failed', 'no_route'));

-- ---- 000012_provider_token_cache.sql ----
CREATE TABLE IF NOT EXISTS provider_token_cache (
    id uuid PRIMARY KEY,
    provider_type text NOT NULL,
    strategy text NOT NULL,
    cache_key text NOT NULL UNIQUE,
    channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL,
    token_url text NOT NULL,
    access_token text NOT NULL DEFAULT '',
    expires_at timestamptz NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    refresh_after_at timestamptz NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    refreshed_at timestamptz NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    invalidated_at timestamptz,
    invalidated_reason text,
    refresh_lock_until timestamptz,
    refresh_lock_owner text,
    last_error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_provider_token_cache_channel
    ON provider_token_cache(channel_id);

CREATE INDEX IF NOT EXISTS idx_provider_token_cache_refresh
    ON provider_token_cache(provider_type, refresh_after_at);

-- ---- 000013_user_identity_channel_scope.sql ----
ALTER TABLE user_identities
    ADD COLUMN IF NOT EXISTS channel_id uuid REFERENCES delivery_channels(id) ON DELETE SET NULL;

ALTER TABLE user_identities
    DROP CONSTRAINT IF EXISTS user_identities_provider_type_identity_kind_identity_value_key;

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_identities_type_default
    ON user_identities(provider_type, identity_kind, identity_value)
    WHERE channel_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_identities_channel_value
    ON user_identities(channel_id, identity_kind, identity_value)
    WHERE channel_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_identities_channel_lookup
    ON user_identities(channel_id, identity_kind, identity_value);

CREATE INDEX IF NOT EXISTS idx_user_identities_user_channel
    ON user_identities(user_id, channel_id, provider_type, identity_kind);

-- ---- 000014_hmac_nonce_dedupe_scope.sql ----
ALTER TABLE dedupe_keys
    DROP CONSTRAINT IF EXISTS dedupe_keys_scope_check;

ALTER TABLE dedupe_keys
    ADD CONSTRAINT dedupe_keys_scope_check
    CHECK (scope IN ('inbound', 'send', 'hmac_nonce'));

ALTER TABLE dedupe_keys
    DROP CONSTRAINT IF EXISTS dedupe_keys_check;

ALTER TABLE dedupe_keys
    ADD CONSTRAINT dedupe_keys_check
    CHECK (
        (scope IN ('inbound', 'hmac_nonce') AND source_id IS NOT NULL AND channel_id IS NULL)
        OR
        (scope = 'send' AND channel_id IS NOT NULL)
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_dedupe_hmac_nonce_source_key
    ON dedupe_keys(scope, source_id, dedupe_key)
    WHERE scope = 'hmac_nonce' AND source_id IS NOT NULL;

-- ---- 000015_dead_letter_handling_state.sql ----
ALTER TABLE dead_letter_jobs
    ADD COLUMN IF NOT EXISTS handled_at timestamptz,
    ADD COLUMN IF NOT EXISTS handled_reason text;

CREATE INDEX IF NOT EXISTS idx_dead_letter_jobs_handled
    ON dead_letter_jobs(handled_at, replayed_at, dead_lettered_at DESC);

-- ---- 000016_audit_resource_text_and_retention.sql ----
ALTER TABLE audit_logs
    ALTER COLUMN resource_id TYPE text USING resource_id::text;

ALTER TABLE retention_cleanup_runs
    ADD COLUMN IF NOT EXISTS deleted_audit_logs integer NOT NULL DEFAULT 0 CHECK (deleted_audit_logs >= 0);

-- ---- 000017_delivery_channel_description.sql ----
ALTER TABLE delivery_channels
    ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';

-- ---- 000018_route_draft_base_version.sql ----
ALTER TABLE route_versions
    ADD COLUMN IF NOT EXISTS draft_base_version_id uuid,
    ADD COLUMN IF NOT EXISTS draft_base_version_no integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_route_versions_draft_base_version_no'
          AND conrelid = 'route_versions'::regclass
    ) THEN
        ALTER TABLE route_versions
            ADD CONSTRAINT ck_route_versions_draft_base_version_no
            CHECK (draft_base_version_no IS NULL OR draft_base_version_no > 0);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_route_versions_draft_base'
          AND conrelid = 'route_versions'::regclass
    ) THEN
        ALTER TABLE route_versions
            ADD CONSTRAINT fk_route_versions_draft_base
            FOREIGN KEY (draft_base_version_id)
            REFERENCES route_versions(id)
            ON DELETE SET NULL;
    END IF;
END $$;

-- ---- 000019_send_job_claim_index.sql ----
CREATE INDEX IF NOT EXISTS idx_jobs_send_claim_ready
ON jobs (
    channel_id,
    priority,
    run_at,
    created_at,
    id
)
WHERE type = 'send_message'
  AND status = 'queued';

-- ---- 000020_admin_login_attempts.sql ----
CREATE TABLE admin_login_attempts (
    attempt_key_hash text PRIMARY KEY,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    window_started_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_login_attempts_updated_at ON admin_login_attempts(updated_at);

-- ---- 000021_log_list_query_indexes.sql ----
CREATE INDEX IF NOT EXISTS idx_message_records_trace_id
    ON message_records(trace_id);

CREATE INDEX IF NOT EXISTS idx_message_records_error_received
    ON message_records(error_code, received_at DESC)
    WHERE error_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_delivery_attempts_message_status
    ON delivery_attempts(message_id, status);

CREATE INDEX IF NOT EXISTS idx_delivery_attempts_message_error
    ON delivery_attempts(message_id, error_code)
    WHERE error_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_delivery_attempts_channel_message
    ON delivery_attempts(channel_id, message_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created
    ON audit_logs(actor_username, created_at DESC)
    WHERE actor_username IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_logs_action_created
    ON audit_logs(action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type_created
    ON audit_logs(resource_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_id_created
    ON audit_logs(resource_id, created_at DESC)
    WHERE resource_id IS NOT NULL;

-- +goose Down

-- Baseline migration is intentionally not reversible.
